version: '3.3'

services:

  db:
    image: mysql:8
    container_name: carService_mysql_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: carservice
      MYSQL_USER: carservceuser
      MYSQL_PASSWORD: toor
    ports:
      - "3306:3306"
    networks:
      - backend

  app:
    image: carservice
    container_name: carService_webapp
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/carservice?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: carserviceuser
      SPRING_DATASOURCE_PASSWORD: toor
    networks:
      - backend

volumes:
  db_data:

networks:
  backend: